language: java
script: gradle test
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
addons:
  sauce_connect:
    username: "mattRedBox"
  jwt:
    secure: EIJqvtoL5lUtPUQ2/5I2XGyKgmB/qlbeA9S/BXEg1aKLhyx4jT9qf45bOxVa0VVzxVLqo5dEKgU56iXSTK57HjFs420R6V1XJoaMvJIcGuvRK0yViGDuc6W88IZtjCMpzxuYBSAUYdXn5o0QmLLIvUdhbRJy1VI3BmuRJQcGj1wF+8WPLTjH9TXukIQHNNlwLvCOdBAfbRT18mq1sElt7tJLu0263McJob1VFQRejES2nrwxwWplZmnq2pml3TkhLuD2oLAhQT1+hlOoitCjjcc9TEE9Fg/DmWJWYBMLXBnObNN0egkf2onXeZMX1V7wGZxnQIVFMFw4lgPRtxzgGIMSr7UnUkQQzR7Hm7665lpoVZCupOoSkVpgdPmUYS3BQ1vXmW4nD4np6PgCB4okQhEgIGXq/r2KgpAUofJ5nVboweF0eSycfL3k4l31b/h/6ymtSSVEhw9qgZ7HUV6GeU7PUYRrIUa9/pNktSeE+Vb4Lo+u3HKuU+9UTHQaiACBjbhYNE5l+jikMIauQD+RT8LlM7rLuTcLYuSDHyhD5F8JA+YfqKdJ10ZUzfGI40dVRg3l+mwYJ2XY96jja5Q5uMbe71pWymmEWgybx3bnwT/eS2bsW7YZOvcyc31kLBjmtal4DPvDGFYalBIpQlfGao9s3+wP9wOGlwlqdrWee78=
